INSERT INTO `teachers_info` VALUES (461, 'li meng', 'EE46', '');
INSERT INTO `teachers_info` VALUES (471, 'Zheng Kai Xuan', 'CE47', NULL);
INSERT INTO `teachers_info` VALUES (472, 'Ou mang', 'CE47', NULL);
INSERT INTO `teachers_info` VALUES (473, 'Xie XiaoJie', 'CE47', NULL);
INSERT INTO `teachers_info` VALUES (474, 'Luo Lin', 'CE47', NULL);
INSERT INTO `teachers_info` VALUES (481, 'li ren', 'PH48', '');
INSERT INTO `teachers_info` VALUES (491, 'Li Yen', 'ME49', NULL);
INSERT INTO `teachers_info` VALUES (501, 'Ouyang', 'CS50', 'XK 402');
INSERT INTO `teachers_info` VALUES (502, 'Sun Bing', 'CS50', '');
INSERT INTO `teachers_info` VALUES (503, 'Li jing jing', 'CS50', '');
INSERT INTO `teachers_info` VALUES (504, 'Mao jian jing', 'CS50', '');
INSERT INTO `teachers_info` VALUES (505, 'TanTongDe', 'CS50', '');
INSERT INTO `teachers_info` VALUES (506, 'Feng  Nai Qin', 'CS50', NULL);
INSERT INTO `teachers_info` VALUES (507, 'Feng Meng Qing', 'CS50', NULL);
INSERT INTO `teachers_info` VALUES (508, 'Yao Yin le', 'CS50', NULL);
